# Generated by Django 4.1.3 on 2022-11-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id_game', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=256)),
                ('date_release', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default='0.00', max_digits=7)),
                ('game_image', models.CharField(default='games/', max_length=512)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.BigAutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id_plat', models.BigAutoField(primary_key=True, serialize=False)),
                ('plat_name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id_pub', models.BigAutoField(primary_key=True, serialize=False)),
                ('pub_name', models.CharField(max_length=256, unique=True)),
                ('year_found', models.IntegerField(blank=True, null=True)),
                ('director', models.CharField(max_length=256, unique=True)),
                ('workers', models.IntegerField(blank=True, null=True)),
                ('pub_image', models.CharField(default='publishers/', max_length=512)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
    ]
