# Generated by Django 4.1.1 on 2022-10-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(verbose_name='Изображение')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('date', models.CharField(max_length=100, verbose_name='Дата')),
                ('descrip', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Игры',
                'db_table': 'games',
                'managed': False,
            },
        ),
    ]
