# Generated by Django 4.1.2 on 2022-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50, verbose_name='Название игры')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр игры')),
                ('publisher', models.CharField(max_length=50, verbose_name='Издатель игры')),
                ('platform', models.CharField(max_length=50, verbose_name='Платформа для игры')),
                ('date_release', models.CharField(max_length=50, verbose_name='Дата выхода')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена игры')),
            ],
        ),
    ]
