# Generated by Django 4.1.2 on 2022-10-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_name', models.CharField(max_length=50, verbose_name='Название компании')),
                ('year_found', models.IntegerField(verbose_name='Год основания')),
                ('director', models.CharField(max_length=50, verbose_name='Глава компании')),
                ('workers', models.IntegerField(verbose_name='Число сотрудников')),
            ],
        ),
    ]
